// PasteboardSnapshot.swift
// KrasipKit
// Saves and restores the user's clipboard around a paste, and writes text clipboard managers should ignore.

import AppKit

@MainActor
struct PasteboardSnapshot {
    private let items: [[(NSPasteboard.PasteboardType, Data)]]

    init(_ pasteboard: NSPasteboard) {
        items = (pasteboard.pasteboardItems ?? []).map { item in
            item.types.compactMap { type in
                item.data(forType: type).map { (type, $0) }
            }
        }
    }

    func restore(to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let restored = items.map { entries -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in entries {
                item.setData(data, forType: type)
            }
            return item
        }
        pasteboard.writeObjects(restored)
    }
}

extension NSPasteboard.PasteboardType {
    /// nspasteboard.org markers: clipboard managers skip transient, auto-generated items.
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

extension NSPasteboard {
    /// Temporary text for a paste; marked so clipboard history apps don't keep it.
    @MainActor
    func writeTransient(_ text: String) {
        clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: .transient)
        item.setData(Data(), forType: .autoGenerated)
        writeObjects([item])
    }

    /// Text the user is meant to paste themselves.
    @MainActor
    func writeForUser(_ text: String) {
        clearContents()
        setString(text, forType: .string)
    }
}
